services:
  - type: web
    name: gemini-api
    env: node
    build_command: npm install
    start_command: npm start
    env_vars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
